using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SecureQrPortal.Data;

#nullable disable
namespace SecureQrPortal.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("202608250001_InitialCreate")]
public sealed class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        if (ActiveProvider.Contains("Sqlite", StringComparison.OrdinalIgnoreCase)) migrationBuilder.Sql(SqliteSql);
        else if (ActiveProvider.Contains("SqlServer", StringComparison.OrdinalIgnoreCase)) migrationBuilder.Sql(SqlServerSql);
        else throw new NotSupportedException($"Unsupported database provider {ActiveProvider}");
    }
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        if (ActiveProvider.Contains("Sqlite", StringComparison.OrdinalIgnoreCase)) migrationBuilder.Sql(SqliteDown);
        else migrationBuilder.Sql(SqlServerDown);
    }
    private const string SqliteSql = """
CREATE TABLE "AspNetRoles" ("Id" TEXT NOT NULL PRIMARY KEY,"Name" TEXT NULL,"NormalizedName" TEXT NULL,"ConcurrencyStamp" TEXT NULL);
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE TABLE "AspNetUsers" ("Id" TEXT NOT NULL PRIMARY KEY,"DisplayName" TEXT NOT NULL,"CreatedAtUtc" TEXT NOT NULL,"UserName" TEXT NULL,"NormalizedUserName" TEXT NULL,"Email" TEXT NULL,"NormalizedEmail" TEXT NULL,"EmailConfirmed" INTEGER NOT NULL,"PasswordHash" TEXT NULL,"SecurityStamp" TEXT NULL,"ConcurrencyStamp" TEXT NULL,"PhoneNumber" TEXT NULL,"PhoneNumberConfirmed" INTEGER NOT NULL,"TwoFactorEnabled" INTEGER NOT NULL,"LockoutEnd" TEXT NULL,"LockoutEnabled" INTEGER NOT NULL,"AccessFailedCount" INTEGER NOT NULL);
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE TABLE "AspNetRoleClaims" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"RoleId" TEXT NOT NULL,"ClaimType" TEXT NULL,"ClaimValue" TEXT NULL,FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE);
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims"("RoleId");
CREATE TABLE "AspNetUserClaims" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"UserId" TEXT NOT NULL,"ClaimType" TEXT NULL,"ClaimValue" TEXT NULL,FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE);
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims"("UserId");
CREATE TABLE "AspNetUserLogins" ("LoginProvider" TEXT NOT NULL,"ProviderKey" TEXT NOT NULL,"ProviderDisplayName" TEXT NULL,"UserId" TEXT NOT NULL,PRIMARY KEY("LoginProvider","ProviderKey"),FOREIGN KEY("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE);
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins"("UserId");
CREATE TABLE "AspNetUserRoles" ("UserId" TEXT NOT NULL,"RoleId" TEXT NOT NULL,PRIMARY KEY("UserId","RoleId"),FOREIGN KEY("RoleId") REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE,FOREIGN KEY("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE);
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles"("RoleId");
CREATE TABLE "AspNetUserTokens" ("UserId" TEXT NOT NULL,"LoginProvider" TEXT NOT NULL,"Name" TEXT NOT NULL,"Value" TEXT NULL,PRIMARY KEY("UserId","LoginProvider","Name"),FOREIGN KEY("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE);
CREATE TABLE "Organizations" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"NameArabic" TEXT NOT NULL,"NameEnglish" TEXT NOT NULL,"LogoPath" TEXT NULL,"IsActive" INTEGER NOT NULL,"IsDemo" INTEGER NOT NULL,"CreatedAtUtc" TEXT NOT NULL,"UpdatedAtUtc" TEXT NOT NULL);
CREATE INDEX "IX_Organizations_NameArabic" ON "Organizations"("NameArabic"); CREATE INDEX "IX_Organizations_NameEnglish" ON "Organizations"("NameEnglish");
CREATE TABLE "SecurePages" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"OrganizationId" INTEGER NOT NULL,"QrReference" TEXT NOT NULL,"PublicTokenHash" TEXT NOT NULL,"ProtectedPublicToken" TEXT NOT NULL,"CurrentTokenCreatedAtUtc" TEXT NOT NULL,"TitleArabic" TEXT NOT NULL,"TitleEnglish" TEXT NOT NULL,"ContentArabicHtml" TEXT NOT NULL,"ContentEnglishHtml" TEXT NOT NULL,"IsActive" INTEGER NOT NULL,"ValidFromUtc" TEXT NULL,"ExpiresAtUtc" TEXT NULL,"AccessLimitMode" INTEGER NOT NULL,"MaxAccessCount" INTEGER NULL,"CurrentSuccessfulAccessCount" INTEGER NOT NULL,"CurrentQrOpenCount" INTEGER NOT NULL,"CurrentSuccessfulLoginCount" INTEGER NOT NULL,"CurrentFailedLoginCount" INTEGER NOT NULL,"LastQrScanAtUtc" TEXT NULL,"LastSuccessfulAccessAtUtc" TEXT NULL,"RevokedAtUtc" TEXT NULL,"CreatedByAdminId" TEXT NULL,"LastModifiedByAdminId" TEXT NULL,"CreatedAtUtc" TEXT NOT NULL,"UpdatedAtUtc" TEXT NOT NULL,"IsDemo" INTEGER NOT NULL,"ConcurrencyStamp" TEXT NOT NULL,FOREIGN KEY("OrganizationId") REFERENCES "Organizations"("Id") ON DELETE RESTRICT);
CREATE UNIQUE INDEX "IX_SecurePages_QrReference" ON "SecurePages"("QrReference"); CREATE UNIQUE INDEX "IX_SecurePages_PublicTokenHash" ON "SecurePages"("PublicTokenHash"); CREATE INDEX "IX_SecurePages_OrganizationId_CreatedAtUtc" ON "SecurePages"("OrganizationId","CreatedAtUtc");
CREATE TABLE "PageCredentials" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"SecurePageId" INTEGER NOT NULL,"Username" TEXT NOT NULL,"PasswordHash" TEXT NOT NULL,"UpdatedAtUtc" TEXT NOT NULL,FOREIGN KEY("SecurePageId") REFERENCES "SecurePages"("Id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "IX_PageCredentials_SecurePageId" ON "PageCredentials"("SecurePageId"); CREATE UNIQUE INDEX "IX_PageCredentials_SecurePageId_Username" ON "PageCredentials"("SecurePageId","Username");
CREATE TABLE "AccessLogs" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"SecurePageId" INTEGER NULL,"EventType" TEXT NOT NULL,"TimestampUtc" TEXT NOT NULL,"IpAddress" TEXT NULL,"UserAgent" TEXT NULL,"DeviceType" TEXT NULL,"Browser" TEXT NULL,"Country" TEXT NULL,"WasSuccessful" INTEGER NOT NULL,"FailureReasonInternal" TEXT NULL,FOREIGN KEY("SecurePageId") REFERENCES "SecurePages"("Id") ON DELETE SET NULL);
CREATE INDEX "IX_AccessLogs_SecurePageId_TimestampUtc" ON "AccessLogs"("SecurePageId","TimestampUtc"); CREATE INDEX "IX_AccessLogs_EventType_TimestampUtc" ON "AccessLogs"("EventType","TimestampUtc");
CREATE TABLE "QrTokenHistories" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"SecurePageId" INTEGER NOT NULL,"PreviousTokenHash" TEXT NOT NULL,"CreatedAtUtc" TEXT NOT NULL,"RevokedAtUtc" TEXT NOT NULL,"RevokedByAdminId" TEXT NULL,"RevocationReason" TEXT NULL,"ReplacementTokenCreatedAtUtc" TEXT NULL,FOREIGN KEY("SecurePageId") REFERENCES "SecurePages"("Id") ON DELETE CASCADE);
CREATE INDEX "IX_QrTokenHistories_SecurePageId_RevokedAtUtc" ON "QrTokenHistories"("SecurePageId","RevokedAtUtc");
CREATE TABLE "ApplicationSettings" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"Key" TEXT NOT NULL,"Value" TEXT NOT NULL,"UpdatedAtUtc" TEXT NOT NULL); CREATE UNIQUE INDEX "IX_ApplicationSettings_Key" ON "ApplicationSettings"("Key");
CREATE TABLE "AuditLogs" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"AdminUserId" TEXT NULL,"Action" TEXT NOT NULL,"EntityType" TEXT NOT NULL,"EntityId" TEXT NULL,"Details" TEXT NULL,"TimestampUtc" TEXT NOT NULL,"IpAddress" TEXT NULL); CREATE INDEX "IX_AuditLogs_TimestampUtc" ON "AuditLogs"("TimestampUtc");
""";
    private const string SqlServerSql = """
CREATE TABLE [AspNetRoles]([Id] nvarchar(450) NOT NULL PRIMARY KEY,[Name] nvarchar(256) NULL,[NormalizedName] nvarchar(256) NULL,[ConcurrencyStamp] nvarchar(max) NULL); CREATE UNIQUE INDEX [RoleNameIndex] ON [AspNetRoles]([NormalizedName]) WHERE [NormalizedName] IS NOT NULL;
CREATE TABLE [AspNetUsers]([Id] nvarchar(450) NOT NULL PRIMARY KEY,[DisplayName] nvarchar(max) NOT NULL,[CreatedAtUtc] datetime2 NOT NULL,[UserName] nvarchar(256) NULL,[NormalizedUserName] nvarchar(256) NULL,[Email] nvarchar(256) NULL,[NormalizedEmail] nvarchar(256) NULL,[EmailConfirmed] bit NOT NULL,[PasswordHash] nvarchar(max) NULL,[SecurityStamp] nvarchar(max) NULL,[ConcurrencyStamp] nvarchar(max) NULL,[PhoneNumber] nvarchar(max) NULL,[PhoneNumberConfirmed] bit NOT NULL,[TwoFactorEnabled] bit NOT NULL,[LockoutEnd] datetimeoffset NULL,[LockoutEnabled] bit NOT NULL,[AccessFailedCount] int NOT NULL); CREATE UNIQUE INDEX [UserNameIndex] ON [AspNetUsers]([NormalizedUserName]) WHERE [NormalizedUserName] IS NOT NULL; CREATE INDEX [EmailIndex] ON [AspNetUsers]([NormalizedEmail]);
CREATE TABLE [AspNetRoleClaims]([Id] int IDENTITY(1,1) NOT NULL PRIMARY KEY,[RoleId] nvarchar(450) NOT NULL,[ClaimType] nvarchar(max) NULL,[ClaimValue] nvarchar(max) NULL,CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId] FOREIGN KEY([RoleId]) REFERENCES [AspNetRoles]([Id]) ON DELETE CASCADE); CREATE INDEX [IX_AspNetRoleClaims_RoleId] ON [AspNetRoleClaims]([RoleId]);
CREATE TABLE [AspNetUserClaims]([Id] int IDENTITY(1,1) NOT NULL PRIMARY KEY,[UserId] nvarchar(450) NOT NULL,[ClaimType] nvarchar(max) NULL,[ClaimValue] nvarchar(max) NULL,CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers]([Id]) ON DELETE CASCADE); CREATE INDEX [IX_AspNetUserClaims_UserId] ON [AspNetUserClaims]([UserId]);
CREATE TABLE [AspNetUserLogins]([LoginProvider] nvarchar(128) NOT NULL,[ProviderKey] nvarchar(128) NOT NULL,[ProviderDisplayName] nvarchar(max) NULL,[UserId] nvarchar(450) NOT NULL,CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY([LoginProvider],[ProviderKey]),CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers]([Id]) ON DELETE CASCADE); CREATE INDEX [IX_AspNetUserLogins_UserId] ON [AspNetUserLogins]([UserId]);
CREATE TABLE [AspNetUserRoles]([UserId] nvarchar(450) NOT NULL,[RoleId] nvarchar(450) NOT NULL,CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY([UserId],[RoleId]),CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY([RoleId]) REFERENCES [AspNetRoles]([Id]) ON DELETE CASCADE,CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers]([Id]) ON DELETE CASCADE); CREATE INDEX [IX_AspNetUserRoles_RoleId] ON [AspNetUserRoles]([RoleId]);
CREATE TABLE [AspNetUserTokens]([UserId] nvarchar(450) NOT NULL,[LoginProvider] nvarchar(128) NOT NULL,[Name] nvarchar(128) NOT NULL,[Value] nvarchar(max) NULL,CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY([UserId],[LoginProvider],[Name]),CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers]([Id]) ON DELETE CASCADE);
CREATE TABLE [Organizations]([Id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,[NameArabic] nvarchar(200) NOT NULL,[NameEnglish] nvarchar(200) NOT NULL,[LogoPath] nvarchar(400) NULL,[IsActive] bit NOT NULL,[IsDemo] bit NOT NULL,[CreatedAtUtc] datetime2 NOT NULL,[UpdatedAtUtc] datetime2 NOT NULL); CREATE INDEX [IX_Organizations_NameArabic] ON [Organizations]([NameArabic]); CREATE INDEX [IX_Organizations_NameEnglish] ON [Organizations]([NameEnglish]);
CREATE TABLE [SecurePages]([Id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,[OrganizationId] bigint NOT NULL,[QrReference] nvarchar(32) NOT NULL,[PublicTokenHash] nvarchar(64) NOT NULL,[ProtectedPublicToken] nvarchar(max) NOT NULL,[CurrentTokenCreatedAtUtc] datetime2 NOT NULL,[TitleArabic] nvarchar(250) NOT NULL,[TitleEnglish] nvarchar(250) NOT NULL,[ContentArabicHtml] nvarchar(max) NOT NULL,[ContentEnglishHtml] nvarchar(max) NOT NULL,[IsActive] bit NOT NULL,[ValidFromUtc] datetime2 NULL,[ExpiresAtUtc] datetime2 NULL,[AccessLimitMode] int NOT NULL,[MaxAccessCount] bigint NULL,[CurrentSuccessfulAccessCount] bigint NOT NULL,[CurrentQrOpenCount] bigint NOT NULL,[CurrentSuccessfulLoginCount] bigint NOT NULL,[CurrentFailedLoginCount] bigint NOT NULL,[LastQrScanAtUtc] datetime2 NULL,[LastSuccessfulAccessAtUtc] datetime2 NULL,[RevokedAtUtc] datetime2 NULL,[CreatedByAdminId] nvarchar(450) NULL,[LastModifiedByAdminId] nvarchar(450) NULL,[CreatedAtUtc] datetime2 NOT NULL,[UpdatedAtUtc] datetime2 NOT NULL,[IsDemo] bit NOT NULL,[ConcurrencyStamp] nvarchar(36) NOT NULL,CONSTRAINT [FK_SecurePages_Organizations_OrganizationId] FOREIGN KEY([OrganizationId]) REFERENCES [Organizations]([Id])); CREATE UNIQUE INDEX [IX_SecurePages_QrReference] ON [SecurePages]([QrReference]); CREATE UNIQUE INDEX [IX_SecurePages_PublicTokenHash] ON [SecurePages]([PublicTokenHash]); CREATE INDEX [IX_SecurePages_OrganizationId_CreatedAtUtc] ON [SecurePages]([OrganizationId],[CreatedAtUtc]);
CREATE TABLE [PageCredentials]([Id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,[SecurePageId] bigint NOT NULL,[Username] nvarchar(150) NOT NULL,[PasswordHash] nvarchar(max) NOT NULL,[UpdatedAtUtc] datetime2 NOT NULL,CONSTRAINT [FK_PageCredentials_SecurePages_SecurePageId] FOREIGN KEY([SecurePageId]) REFERENCES [SecurePages]([Id]) ON DELETE CASCADE); CREATE UNIQUE INDEX [IX_PageCredentials_SecurePageId] ON [PageCredentials]([SecurePageId]); CREATE UNIQUE INDEX [IX_PageCredentials_SecurePageId_Username] ON [PageCredentials]([SecurePageId],[Username]);
CREATE TABLE [AccessLogs]([Id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,[SecurePageId] bigint NULL,[EventType] nvarchar(60) NOT NULL,[TimestampUtc] datetime2 NOT NULL,[IpAddress] nvarchar(64) NULL,[UserAgent] nvarchar(700) NULL,[DeviceType] nvarchar(80) NULL,[Browser] nvarchar(80) NULL,[Country] nvarchar(80) NULL,[WasSuccessful] bit NOT NULL,[FailureReasonInternal] nvarchar(250) NULL,CONSTRAINT [FK_AccessLogs_SecurePages_SecurePageId] FOREIGN KEY([SecurePageId]) REFERENCES [SecurePages]([Id]) ON DELETE SET NULL); CREATE INDEX [IX_AccessLogs_SecurePageId_TimestampUtc] ON [AccessLogs]([SecurePageId],[TimestampUtc]); CREATE INDEX [IX_AccessLogs_EventType_TimestampUtc] ON [AccessLogs]([EventType],[TimestampUtc]);
CREATE TABLE [QrTokenHistories]([Id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,[SecurePageId] bigint NOT NULL,[PreviousTokenHash] nvarchar(64) NOT NULL,[CreatedAtUtc] datetime2 NOT NULL,[RevokedAtUtc] datetime2 NOT NULL,[RevokedByAdminId] nvarchar(450) NULL,[RevocationReason] nvarchar(250) NULL,[ReplacementTokenCreatedAtUtc] datetime2 NULL,CONSTRAINT [FK_QrTokenHistories_SecurePages_SecurePageId] FOREIGN KEY([SecurePageId]) REFERENCES [SecurePages]([Id]) ON DELETE CASCADE); CREATE INDEX [IX_QrTokenHistories_SecurePageId_RevokedAtUtc] ON [QrTokenHistories]([SecurePageId],[RevokedAtUtc]);
CREATE TABLE [ApplicationSettings]([Id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,[Key] nvarchar(160) NOT NULL,[Value] nvarchar(max) NOT NULL,[UpdatedAtUtc] datetime2 NOT NULL); CREATE UNIQUE INDEX [IX_ApplicationSettings_Key] ON [ApplicationSettings]([Key]);
CREATE TABLE [AuditLogs]([Id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,[AdminUserId] nvarchar(450) NULL,[Action] nvarchar(120) NOT NULL,[EntityType] nvarchar(120) NOT NULL,[EntityId] nvarchar(120) NULL,[Details] nvarchar(2000) NULL,[TimestampUtc] datetime2 NOT NULL,[IpAddress] nvarchar(64) NULL); CREATE INDEX [IX_AuditLogs_TimestampUtc] ON [AuditLogs]([TimestampUtc]);
""";
    private const string SqliteDown = """DROP TABLE IF EXISTS "AspNetRoleClaims"; DROP TABLE IF EXISTS "AspNetUserClaims"; DROP TABLE IF EXISTS "AspNetUserLogins"; DROP TABLE IF EXISTS "AspNetUserRoles"; DROP TABLE IF EXISTS "AspNetUserTokens"; DROP TABLE IF EXISTS "QrTokenHistories"; DROP TABLE IF EXISTS "AccessLogs"; DROP TABLE IF EXISTS "PageCredentials"; DROP TABLE IF EXISTS "SecurePages"; DROP TABLE IF EXISTS "Organizations"; DROP TABLE IF EXISTS "ApplicationSettings"; DROP TABLE IF EXISTS "AuditLogs"; DROP TABLE IF EXISTS "AspNetRoles"; DROP TABLE IF EXISTS "AspNetUsers";""";
    private const string SqlServerDown = """DROP TABLE [AspNetRoleClaims]; DROP TABLE [AspNetUserClaims]; DROP TABLE [AspNetUserLogins]; DROP TABLE [AspNetUserRoles]; DROP TABLE [AspNetUserTokens]; DROP TABLE [QrTokenHistories]; DROP TABLE [AccessLogs]; DROP TABLE [PageCredentials]; DROP TABLE [SecurePages]; DROP TABLE [Organizations]; DROP TABLE [ApplicationSettings]; DROP TABLE [AuditLogs]; DROP TABLE [AspNetRoles]; DROP TABLE [AspNetUsers];""";
}
